# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0166588adff9b200f50e6103c5cb8e304dfeb5c6a93e57dd059c7d0169c9d333a003faa34245ee72b25bf140f9bb8b4617e3fb25e263453e14e1fbee98876f7

test:
  secret_key_base: 2997f066226919f503b3418bf817be8eb96bcf9bdc673eafb90b35b17bfb6fdc5ccc5ed60a24e1d431c993f28c8ad4fca93adebee7801db8a589140b6d788a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
